name: Matrix Include with Label

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
        include:
          - python-version: "3.12"
            label: "preview"
    name: Build (py ${{ matrix.python-version }} ${{ matrix.label }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print matrix info
        run: |
          echo "Matrix python-version=${{ matrix.python-version }}"
          echo "Label='${{ matrix.label }}'"
