name: Name inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: false
        default: 'friend'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: 'Say hello'
       run: echo "Hello, ${{ github.event.inputs.name }}!"
